<?php
declare(strict_types=1);
if (!defined('ABSPATH')) exit;

$cron = $data['cron'] ?? [];
$hooks = $cron['hooks'] ?? [];
?>
<div class="page-header d-print-none"><div class="container-xl"><div class="row g-2 align-items-center"><div class="col"><div class="page-pretitle">Info & Diagnose</div><h2 class="page-title">Cron-Job Status</h2><div class="text-secondary mt-1">Erkennt registrierte Cron-Hooks im Codebestand und zeigt, ob ein zentrales Cron-Skript vorhanden ist.</div></div></div></div></div>
<div class="page-body"><div class="container-xl"><?php if (!empty($alert)): ?><div class="alert alert-<?php echo htmlspecialchars($alert['type'] ?? 'info'); ?> mb-4"><?php echo htmlspecialchars($alert['message'] ?? ''); ?></div><?php endif; ?><?php require __DIR__ . '/subnav.php'; ?><div class="row row-deck row-cards mb-4"><div class="col-md-4"><div class="card"><div class="card-body"><div class="subheader">Cron-Datei</div><div class="h1 mb-0 <?php echo !empty($cron['cron_file_exists']) ? 'text-success' : 'text-warning'; ?>"><?php echo !empty($cron['cron_file_exists']) ? 'Vorhanden' : 'Nicht gefunden'; ?></div></div></div></div><div class="col-md-4"><div class="card"><div class="card-body"><div class="subheader">Registrierte Hooks</div><div class="h1 mb-0"><?php echo (int)($cron['hook_count'] ?? 0); ?></div></div></div></div></div><div class="card"><div class="card-header"><h3 class="card-title">Gefundene Cron-Hooks</h3></div><div class="table-responsive"><table class="table table-vcenter card-table table-striped"><thead><tr><th>Hook</th><th>Vorkommen</th><th>Quelldateien</th></tr></thead><tbody><?php if (empty($hooks)): ?><tr><td colspan="3" class="text-center text-secondary py-4">Keine registrierten Cron-Hooks gefunden.</td></tr><?php else: ?><?php foreach ($hooks as $hook): ?><tr><td><code><?php echo htmlspecialchars((string)$hook['hook']); ?></code></td><td><?php echo (int)$hook['occurrences']; ?></td><td class="text-break"><?php echo htmlspecialchars(implode(', ', (array)$hook['files'])); ?></td></tr><?php endforeach; ?><?php endif; ?></tbody></table></div></div></div></div>
