<?php
declare(strict_types=1);
if (!defined('ABSPATH')) exit;
if (!defined('CMS_ADMIN_SYSTEM_VIEW')) exit;

$response = $data['monitoring']['response_time'] ?? [];
$settings = $data['email_alerts'] ?? [];
?>
<div class="page-header d-print-none"><div class="container-xl"><div class="row g-2 align-items-center"><div class="col"><div class="page-pretitle">Info & Diagnose</div><h2 class="page-title">Response-Time Monitoring</h2><div class="text-secondary mt-1">Misst die aktuelle Antwortzeit der Hauptseite gegen die gespeicherte Schwelle.</div></div></div></div></div>
<div class="page-body"><div class="container-xl"><?php $alertData = $alert; $alertMarginClass = 'mb-4'; require __DIR__ . '/../partials/flash-alert.php'; ?><?php require __DIR__ . '/subnav.php'; ?><div class="row row-deck row-cards mb-4"><div class="col-md-4"><div class="card"><div class="card-body"><div class="subheader">Antwortzeit</div><div class="h1 mb-0"><?php echo (int)($response['duration_ms'] ?? 0); ?> ms</div><div class="text-secondary">Schwelle: <?php echo (int)($settings['monitor_response_threshold_ms'] ?? 800); ?> ms</div></div></div></div><div class="col-md-4"><div class="card"><div class="card-body"><div class="subheader">HTTP-Status</div><div class="h1 mb-0"><?php echo (int)($response['status_code'] ?? 0); ?></div></div></div></div><div class="col-md-4"><div class="card"><div class="card-body"><div class="subheader">Ergebnis</div><div class="h1 mb-0 <?php echo empty($response['error']) ? 'text-success' : 'text-danger'; ?>"><?php echo empty($response['error']) ? 'OK' : 'Fehler'; ?></div></div></div></div></div><div class="card"><div class="card-header"><h3 class="card-title">Messdetails</h3></div><div class="table-responsive"><table class="table table-vcenter card-table"><tbody><tr><td class="text-muted w-25">URL</td><td class="text-break"><?php echo htmlspecialchars((string)($response['url'] ?? '')); ?></td></tr><tr><td class="text-muted">Fehler</td><td><?php echo htmlspecialchars((string)($response['error'] ?? 'Keiner')); ?></td></tr></tbody></table></div></div></div></div>
